version: '2'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: robo
    networks:
      - db-mongo
      - db-elastic
      - db-redis
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  mongo-express:
    image: mongo-express:latest
    container_name: mongodb-admin
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    links:
      - mongodb
    networks:
      - db-mongo
      - frontend-db-manager

  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ELASTICSEARCH_NODE_PORT_NUMBER=9300
    volumes:
      - ./elastic-data:/bitnami/elasticsearch/data
    networks:
      - db-elastic

  redis:
    image: 'redis:latest'
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
      - 6380:6380
    volumes:
      - ./redis-data:/data
    networks:
      - db-redis

networks:
  frontend-db-manager:
    driver: bridge
  db-mongo:
    driver: bridge
  db-elastic:
    driver: bridge
  db-redis:
    driver: bridge
